### ISSUE TITLE
Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by YCAyca** [timesler/facenet-pytorch#132]
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print('Running on device: {}'.format(device))  #cuda
mtcnn = MTCNN(
    image_size=160, margin=0, min_face_size=20,
    thresholds=[0.6, 0.7, 0.7], factor=0.709, post_process=True,
    device=device
)
print('Running on device: {}'.format(mtcnn.device)) #cuda
resnet = InceptionResnetV1(pretrained='vggface2').eval().to(device) 
print('Running on device: {}'.format(mtcnn.device)) #cuda

I'm getting "Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same" error which means the data is getting load as cuda Tensor but weights are getting load as cpu Tensor. I dont know what else to do to get weights load as cuda Tensor. I tried to clear the weight cache and load them again (because at first I was usign the model in cpu so I thought maybe the weights are stored already in cpu cache and I cant get them on cuda etc). 

I tried to change the order of loading model and weights

resnet = InceptionResnetV1(classify=True, num_classes=(8631)).eval()
resnet.cuda()
resnet.load_weights("vggface2")

I tried to use this one 
resnet = InceptionResnetV1(pretrained='vggface2', device = device).eval()

but anyway I cant load the weights on cuda and keep getting that error. Anyone has any idea? #cudaerror

**Comment by YCAyca** [comment]
![image](https://user-images.githubusercontent.com/20625822/95881804-441eb880-0d79-11eb-8a31-554c2caf6e95.png)

And actually I have changed 1 line in each source file in mtcnn.py and inception_resnet_v1.py. Because it was implemented wrongly and even if the user wants to use cuda and put cuda as the device using device = torch.device("cuda"), the program was putting cpu without lookind the device. So while print('Running on device: {}'.format(device)) was printing "cuda" on the output screen, 
mtcnn = MTCNN(
    image_size=160, margin=0, min_face_size=20,
    thresholds=[0.6, 0.7, 0.7], factor=0.709, post_process=True,
    device=device
)
print('Running on device: {}'.format(mtcnn.device)) was printing "cpu".  

So I changed as I show and use facenet-pytorch like that now.

**Comment by YCAyca** [comment]
Ok I guess there was a misunderstood I dont know why I see that the original code contains 
self.device = torch.device('cpu')
        if device is not None:
            self.device = device
            self.to(device)
statements and it works already properly.

**Comment by zj837578609** [comment]
HOW  to solve the problem?  help
